modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="msmod"
version="1.0.0"
displayName="MS-MOD"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="buskmoose, MCreator"

[[dependencies.msmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



